name: my_env
channels:
  - conda-forge
  - defaults
dependencies:
  # This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
  - absl-py=2.1.0                                   
  - anyio=4.3.0                                         
  - aom=3.8.1                                          
  - argon2-cffi=23.1.0                                         
  - argon2-cffi-bindings=21.2.0                                             
  - arrow=1.3.0                                         
  - asttokens=2.4.1                                         
  - astunparse=1.6.3                                   
  - async-lru=2.0.4                                         
  - attrs=23.2.0                                          
  - av=11.0.0                                   
  - babel=2.14.0                                         
  - beautifulsoup4=4.12.3                                         
  - bleach=6.1.0                                         
  - brotli=1.1.0                                     
  - brotli-bin=1.1.0                                     
  - brotli-python=1.1.0                                             
  - bzip2=1.0.8                                     
  - ca-certificates=2024.7.4                                          
  - cached-property=1.5.2                                         
  - cached_property=1.5.2                                         
  - cachetools=5.3.2                                   
  - cairo=1.18.0                                          
  - certifi=2024.7.4                                         
  - cffi=1.16.0                                             
  - charset-normalizer=3.3.2                                         
  - click=8.1.7                                              
  - cloudpickle=3.0.0                                         
  - colorama=0.4.6                                         
  - comm=0.2.1                                         
  - contourpy=1.2.0                                             
  - cudatoolkit=11.2.2                                           
  - cudnn=8.1.0.77                                          
  - cycler=0.12.1                                         
  - cytoolz=0.12.3                                             
  - dask-core=2024.2.1                                         
  - dav1d=1.2.1                                     
  - debugpy=1.8.1                                             
  - decorator=5.1.1                                         
  - defusedxml=0.7.1                                         
  - entrypoints=0.4                                         
  - exceptiongroup=1.2.0                                         
  - executing=2.0.1                                         
  - expat=2.5.0                                          
  - ffmpeg=6.1.1                                              
  - flatbuffers=23.5.26                                   
  - font-ttf-dejavu-sans-mono=2.37                                        
  - font-ttf-inconsolata=3.000                                          
  - font-ttf-source-code-pro=2.038                                          
  - font-ttf-ubuntu=0.83                                          
  - fontconfig=2.14.2                                       
  - fonts-conda-ecosystem=1=0                                              
  - fonts-conda-forge=1=0                                              
  - fonttools=4.49.0                                             
  - fqdn=1.5.1                                         
  - freeglut=3.2.2                                          
  - freetype=2.12.1                                       
  - fsspec=2024.2.0                                        
  - gast=0.4.0                                   
  - gettext=0.21.1                                          
  - glib=2.78.4                                          
  - glib-tools=2.78.4                                          
  - google-auth=2.28.0                                   
  - google-auth-oauthlib=0.4.6                                   
  - google-pasta=0.2.0                                   
  - graphite2=1.3.13=1000                                              
  - grpcio=1.60.1                                   
  - gst-plugins-base=1.22.9                                          
  - gstreamer=1.22.9                                         
  - h11=0.14.0                                         
  - h2=4.1.0                                         
  - h5py=3.10.0                                   
  - harfbuzz=8.3.0                                          
  - hdf5=1.14.3                                              
  - hpack=4.0.0                                          
  - httpcore=1.0.3                                         
  - httpx=0.26.0                                         
  - hyperframe=6.0.1                                         
  - icu=73.2                                          
  - idna=3.6                                         
  - imagecodecs-lite=2019.12.3                                             
  - imageio=2.34.0                                          
  - importlib-metadata=7.0.1                                         
  - importlib-resources=6.1.1                                         
  - importlib_metadata=7.0.1                                         
  - importlib_resources=6.1.1                                         
  - imutils=0.5.4                                             
  - intel-openmp=2024.0.0                                              
  - ipykernel=6.29.2                                         
  - ipython=8.18.1                                          
  - isoduration=20.11.0                                         
  - jasper=4.2.0                                          
  - jedi=0.19.1                                         
  - jinja2=3.1.3                                         
  - joblib=1.4.2                                         
  - json5=0.9.14                                         
  - jsonpointer=2.4                                             
  - jsonschema=4.21.1                                         
  - jsonschema-specifications=2023.12.1                                         
  - jsonschema-with-format-nongpl=4.21.1                                         
  - jupyter-lsp=2.2.2                                         
  - jupyter_client=8.6.0                                         
  - jupyter_core=5.7.1                                             
  - jupyter_events=0.9.0                                         
  - jupyter_server=2.12.5                                         
  - jupyter_server_terminals=0.5.2                                         
  - jupyterlab=4.1.1                                         
  - jupyterlab_pygments=0.3.0                                         
  - jupyterlab_server=2.25.3                                         
  - keras=2.10.0                                   
  - keras-preprocessing=1.1.2                                   
  - khronos-opencl-icd-loader=2023.04.17                                          
  - kiwisolver=1.4.5                                             
  - krb5=1.21.2                                        
  - lazy_loader=0.3                                         
  - lcms2=2.16                                          
  - lerc=4.0.0                                          
  - libabseil=20230802.1                                              
  - libaec=1.1.2                                          
  - libblas=3.9.0=21_win64_mkl                                              
  - libbrotlicommon=1.1.0                                     
  - libbrotlidec=1.1.0                                     
  - libbrotlienc=1.1.0                                     
  - libcblas=3.9.0=21_win64_mkl                                              
  - libclang=16.0.6                                   
  - libclang13=15.0.7                                            
  - libcurl=8.5.0                                         
  - libdeflate=1.19                                     
  - libexpat=2.5.0                                          
  - libffi=3.4.2                                          
  - libglib=2.78.4                                          
  - libhwloc=2.9.39                                              
  - libiconv=1.17                                     
  - libjpeg-turbo=3.0.0                                     
  - liblapack=3.9.0=21_win64_mkl                                              
  - liblapacke=3.9.0=21_win64_mkl                                              
  - libogg=1.3.4                                          
  - libopencv=4.9.0                                             
  - libopenvino=2023.3.0                                         
  - libopenvino-auto-batch-plugin=2023.3.0                                          
  - libopenvino-auto-plugin=2023.3.0                                          
  - libopenvino-hetero-plugin=2023.3.0                                          
  - libopenvino-intel-cpu-plugin=2023.3.0                                         
  - libopenvino-intel-gpu-plugin=2023.3.0                                         
  - libopenvino-ir-frontend=2023.3.0                                          
  - libopenvino-onnx-frontend=2023.3.0                                          
  - libopenvino-paddle-frontend=2023.3.0                                          
  - libopenvino-pytorch-frontend=2023.3.0                                          
  - libopenvino-tensorflow-frontend=2023.3.0                                          
  - libopenvino-tensorflow-lite-frontend=2023.3.0                                          
  - libopus=1.3.1                                          
  - libpng=1.6.42                                          
  - libprotobuf=4.25.1                                         
  - libsodium=1.0.18                                          
  - libsqlite=3.45.1                                     
  - libssh2=1.11.0                                          
  - libtiff=4.6.0                                          
  - libvorbis=1.3.7                                          
  - libwebp-base=1.3.2                                     
  - libxcb=1.15                                        
  - libxml2=2.12.5                                         
  - libzlib=1.2.13                                     
  - locket=1.0.0                                         
  - m2w64-gcc-libgfortran=5.3.0=6                                              
  - m2w64-gcc-libs=5.3.0=7                                              
  - m2w64-gcc-libs-core=5.3.0=7                                              
  - m2w64-gmp=6.1.0=2                                              
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2                                              
  - markdown=3.5.2                                   
  - markupsafe=2.1.5                                             
  - matplotlib=3.8.3                                             
  - matplotlib-base=3.8.3                                             
  - matplotlib-inline=0.1.6                                         
  - mistune=3.0.2                                         
  - mkl=2024.0.0                                              
  - msys2-conda-epoch=20160418=1                                              
  - munkres=1.1.4                                          
  - nbclient=0.8.0                                         
  - nbconvert-core=7.16.1                                         
  - nbformat=5.9.2                                         
  - nest-asyncio=1.6.0                                         
  - networkx=3.2.1                                         
  - notebook=7.1.0                                         
  - notebook-shim=0.2.4                                         
  - numpy=1.26.4                                             
  - oauthlib=3.2.2                                   
  - opencv=4.9.0                                             
  - openh264=2.4.1                                          
  - openjpeg=2.5.0                                          
  - openssl=3.3.1                                          
  - opt-einsum=3.3.0                                   
  - overrides=7.7.0                                         
  - packaging=23.2                                         
  - pandas=2.2.0                                             
  - pandocfilters=1.5.0                                         
  - parso=0.8.3                                         
  - partd=1.4.1                                         
  - pcre2=10.42                                          
  - pickleshare=0.7.5                                      
  - pillow=10.2.0                                             
  - pip=24.0                                         
  - pixman=0.43.2                                          
  - pkgutil-resolve-name=1.3.10                                         
  - platformdirs=4.2.0                                         
  - ply=3.11                                   
  - prometheus_client=0.20.0                                         
  - prompt-toolkit=3.0.42                                         
  - protobuf=3.19.6                                   
  - psutil=5.9.8                                             
  - pthread-stubs=0.4                                           
  - pthreads-win32=2.9.1                                        
  - pugixml=1.14                                          
  - pure_eval=0.2.2                                         
  - py-opencv=4.9.0                                             
  - pyasn1=0.5.1                                   
  - pyasn1-modules=0.3.0                                   
  - pycparser=2.21                                         
  - pygments=2.17.2                                         
  - pyparsing=3.1.1                                         
  - pyqt=5.15.9                                             
  - pyqt5-sip=12.12.2                                             
  - pysocks=1.7.1                                          
  - python=3.9.18thon                                              
  - python-dateutil=2.8.2                                         
  - python-fastjsonschema=2.19.1                                         
  - python-json-logger=2.0.7                                         
  - python-tzdata=2024.1                                         
  - python_abi=3.9=4_cp39                                              
  - pytz=2024.1                                         
  - pywavelets=1.4.1                                             
  - pywin32=306                                             
  - pywinpty=2.0.12                                             
  - pyyaml=6.0.1                                             
  - pyzmq=25.1.2                                             
  - qt-main=5.15.8                                           
  - referencing=0.33.0                                         
  - requests=2.31.0                                         
  - requests-oauthlib=1.3.1                                   
  - rfc3339-validator=0.1.4                                         
  - rfc3986-validator=0.1.1                                          
  - rpds-py=0.18.0                                             
  - rsa=4.9                                   
  - scikit-image=0.20.0                                             
  - scikit-learn=1.5.1                                             
  - scipy=1.9.1                                             
  - send2trash=1.8.2                                          
  - setuptools=69.1.0                                         
  - sip=6.7.12                                             
  - six=1.16.0                                          
  - snappy=1.1.10                                        
  - sniffio=1.3.0                                         
  - soupsieve=2.5                                         
  - stack_data=0.6.2                                         
  - svt-av1=1.8.0                                          
  - tbb=2021.11.0                                          
  - tensorboard=2.10.1                                   
  - tensorboard-data-server=0.6.1                                   
  - tensorboard-plugin-wit=1.8.1                                   
  - tensorflow=2.10.1                                   
  - tensorflow-addons=0.22.0                                   
  - tensorflow-estimator=2.10.0                                   
  - tensorflow-io-gcs-filesystem=0.31.0                                   
  - termcolor=2.4.0                                   
  - terminado=0.18.0                                          
  - threadpoolctl=3.5.0                                         
  - tifffile=2020.6.3                                   
  - tinycss2=1.2.1                                         
  - tk=8.6.13                                          
  - toml=0.10.2                                         
  - tomli=2.0.1                                         
  - toolz=0.12.1                                         
  - tornado=6.3.3                                             
  - traitlets=5.14.1                                         
  - typeguard=2.13.3                                   
  - types-python-dateutil=2.8.19.20240106                                         
  - typing-extensions=4.9.0                                         
  - typing_extensions=4.9.0                                         
  - typing_utils=0.1.0                                         
  - tzdata=2024a                                          
  - ucrt=10.0.22621.0                                          
  - unicodedata2=15.1.0                                             
  - uri-template=1.3.0                                         
  - urllib3=2.2.1                                         
  - vc=14.3                                         
  - vc14_runtime=14.38.33130                                           
  - vs2015_runtime=14.38.33130                                         
  - wcwidth=0.2.13                                         
  - webcolors=1.13                                         
  - webencodings=0.5.1                                         
  - websocket-client=1.7.0                                         
  - werkzeug=3.0.1                                   
  - wheel=0.42.0                                         
  - win_inet_pton=1.1.0                                         
  - winpty=0.4.3=4                                              
  - wrapt=1.16.0                                   
  - x264=1!164.3095                                          
  - x265=3.5                                          
  - xorg-libxau=1.0.11                                        
  - xorg-libxdmcp=1.1.3                                        
  - xz=5.2.6                                          
  - yaml=0.2.5                                          
  - zeromq=4.3.5                                          
  - zipp=3.17.0                                         
  - zlib=1.2.13                                     
  - zstd=1.5.5                                          